name: Deploy Otomatis

on:
  push:
    branches: [ "main" ] # Proses ini berjalan setiap ada push ke branch 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Mengambil kode dari GitHub
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. Menghubungkan ke server dan menjalankan perintah
      - name: Deploy ke Server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST_SAS }}
          username: ${{ secrets.SERVER_USER_SAS }}
          key: ${{ secrets.SSH_PRIVATE_KEY_SAS }}
          # Pastikan tidak ada spasi berlebih di awal baris script
          script: |
            cd /var/www/nama-folder-proyek-anda
            git pull origin main
            npm install
            pm2 restart nama-aplikasi-anda